# Generated by Django 4.2.4 on 2023-09-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('available', models.BooleanField(default=False, verbose_name='Disponible')),
                ('description', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
