# Generated by Django 4.2.4 on 2023-09-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuarto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuarto',
            name='fecha_pago',
            field=models.DateField(null=True),
        ),
    ]
