# Generated by Django 4.2.4 on 2023-09-04 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuarto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrendatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('full_name', models.CharField(blank=True, max_length=120, verbose_name='Nombres Completos')),
                ('contact', models.CharField(max_length=20, verbose_name='Contacto')),
                ('cuarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuarto.cuarto')),
            ],
        ),
    ]
